schema: spec_suite/schema.graphql
input_dir: spec_suite
output_dir: generated
nullable_mode: required
name_prefix: Gql
compress_queries: false
emit_helpers: true
scalars:
  DateTime:
    symbol: AppDateTime
    import: package:shazam/spec_suite/scalars/date_time.dart
